---
- name: restart rgw
  service:
    name: "ceph-radosgw@rgw.{{ ansible_hostname }}.{{ item.instance_name }}"
    state: restarted
  with_items: "{{ rgw_instances }}"

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
  when: haproxy_service_file.stat.exists
