---
# You can override vars by using host or group vars

###########
# GENERAL #
###########

keepalived_build_dir: /opt
keepalived_url: "https://www.keepalived.org/software/keepalived-{{ keepalived_version }}.tar.gz"
keepalived_version: distro

haproxy_frontend_healthcheck: false
haproxy_frontend_port: 80
haproxy_frontend_ssl_port: 443
haproxy_frontend_ssl_termination: False
haproxy_frontend_ssl_certificate:
haproxy_ssl_dh_param: 4096
haproxy_ssl_ciphers:
  - EECDH+AESGCM
  - EDH+AESGCM
haproxy_ssl_options:
  - no-sslv3
  - no-tlsv10
  - no-tlsv11
  - no-tls-tickets
haproxy_stats_socket_group: root
haproxy_stats_socket_mode: '0755'

#virtual_ips:
#  - address: 192.168.238.250
#    netmask: 24
#    interface: ens33
#    virtual_route_gateway:
#    virtual_route_source:
#  - address: 192.168.1.250
#    netmask: 24
#    interface: ens34
#    virtual_route_gateway: 192.168.1.254
#    virtual_route_source:
#      - 10.10.10.1
#      - 10.10.10.2
#      - 10.10.10.3
