---
- name: assert that keepalived_version is defined
  assert:
    that:
      - keepalived_version == 'distro' or keepalived_version is version('0.0.0', '>', strict=True)
    fail_msg: keepalived_version must either be 'distro' or valid version number

- name: install haproxy, keepalived, and make
  package:
    name: ['haproxy', 'keepalived', 'make']
    state: present
  register: result
  until: result is succeeded

- name: install non-distro version of keepalived
  block:
    - name: install required packages for keepalived on debian
      apt:
        name: ['curl', 'gcc', 'libssl-dev', 'libnl-3-dev', 'libnl-genl-3-dev', 'libsnmp-dev']
        state: present
      when: ansible_os_family == 'Debian'

    - name: install required packages for keepalived on redhat
      yum:
        name: ['curl', 'gcc', 'openssl-devel', 'libnl3-devel', 'net-snmp-devel']
        state: present
      when: ansible_os_family == 'RedHat'

    - name: check if specified keepalived version already exists
      command: "ls {{ keepalived_build_dir }}/keepalived-{{ keepalived_version }}"
      failed_when: false
      changed_when: false
      register: _check_keepalived_version

    - name: unarchive keepalived
      unarchive:
        src: "{{ keepalived_url }}"
        dest: "{{ keepalived_build_dir }}/"
        remote_src: true
        owner: root
        group: root
      when: _check_keepalived_version.rc != 0

    - name: build keepalived
      command: './configure'
      args:
        chdir: "{{ keepalived_build_dir }}/keepalived-{{ keepalived_version }}/"
      when: _check_keepalived_version.rc != 0

    - name: install keepalived
      make:
        chdir: "{{ keepalived_build_dir }}/keepalived-{{ keepalived_version }}/"
        target: install
      notify: restart keepalived
      when: _check_keepalived_version.rc != 0

    - name: create systemd override directory
      file:
        path: /etc/systemd/system/keepalived.service.d
        state: directory

    - name: load systemd override file
      copy:
        src: override-execstart.conf
        dest: /etc/systemd/system/keepalived.service.d/override-execstart.conf
      notify:
        - restart keepalived

  when: keepalived_version != 'distro'

- name: "generate haproxy configuration file: haproxy.cfg"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: "root"
    group: "root"
    mode: "0644"
    validate: "haproxy -f %s -c"
  notify:
    - restart haproxy

- name: set_fact vip to vrrp_instance
  set_fact:
      vrrp_instances: "{{ vrrp_instances | default([]) | union([{ 'name': 'VI_' + index|string , 'vip': item.address, 'netmask': item.netmask, 'interface': item.interface, 'virtual_route_gateway': item.virtual_route_gateway, 'virtual_route_source': item.virtual_route_source }]) }}"
  loop: "{{ virtual_ips | flatten(levels=1) }}"
  loop_control:
      index_var: index

- name: "generate keepalived: configuration file: keepalived.conf"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart keepalived
